<a href="https://colab.research.google.com/github/leboneboyer-debug/Simple-Neural-Network-By-Hand/blob/main/SimpleNeuralNetwork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## General Workflow of a Simple Neural Network

Building and training a neural network from scratch involves several key steps:

1.  **Data Preparation**: This involves defining your input features (X) and target outputs (y), as you've done in the `a3aBb8eE1InE` cell.

2.  **Model Initialization**: Randomly initializing the weights and biases for each layer of the network. This was also done in `a3aBb8eE1InE`.

3.  **Forward Propagation**: Passing the input data through the network layers to make predictions. Each layer involves a weighted sum (Z) followed by an activation function (A). You've implemented this in the `4PwTRROvdFMv` cell.

4.  **Loss Calculation**: Quantifying the difference between the network's predictions and the actual target values. Common loss functions include Mean Squared Error (MSE) or Binary Cross-Entropy.

5.  **Backward Propagation (Backpropagation)**: Calculating the gradients of the loss function with respect to each weight and bias in the network. This involves applying the chain rule.

6.  **Weight Update**: Adjusting the weights and biases using an optimization algorithm (like Gradient Descent) to minimize the loss. The new weights are calculated as `weights = weights - learning_rate * gradients`.

7.  **Iteration (Epochs)**: Repeating steps 3-6 for a specified number of epochs (training iterations) to allow the network to learn and improve its predictions.

In [16]:
# Attempting to build a neural network by scratch, using only numpy as the only package
!pip install numpy

In [17]:
import numpy as np

# 1. Simple Neural Network
## a. Random Initialization of Input Data
X = np.array([[0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1]],
             dtype = float)

y = np.array([[0],
              [1],
              [1],
              [0]],
             dtype = float)

## b. Initialization of Weights and Bias

# Corrected shape for weights1 to match X's columns
weights1 = np.random.randn(3,3)

bias1 = np.zeros((1,3))

weights2 = np.random.randn(3,1)

bias2 = np.zeros((1,1))

print(f"First set of Weights:\n {weights1}")
print(f"First set of Bias:\n {bias1}")
print(f"Second set of Weights:\n {weights2}")
print(f"Second set of Bias:\n {bias2}")

First set of Weights:
 [[-0.65341947  1.4053985  -0.26802901]
 [-0.39972969 -2.2354862  -1.85382691]
 [ 0.6058675   0.24854609  1.76899684]]
First set of Bias:
 [[0. 0. 0.]]
Second set of Weights:
 [[1.76226951]
 [0.72094038]
 [1.30503066]]
Second set of Bias:
 [[0.]]


In [18]:
## c. Forward Propogation & Activation Function

# Using Sigmoid for activation function
def sigmoid(x):
  return (1/(1+np.exp(-x)))

def sigmoid_derivative(x):
  return x*(1-x)

## Forward Propogation through simple matrix multiplication

Z1 = X@weights1 + bias1

A1 = sigmoid(Z1)

Z2 = A1@weights2 + bias2

A2 = sigmoid(Z2)

print(f"First set of Z:\n {Z1}")
print(f"First set of A:\n {A1}")
print(f"Second set of Z:\n {Z2}")
print(f"Second set of A:\n {A2}")


First set of Z:
 [[ 0.6058675   0.24854609  1.76899684]
 [ 0.2061378  -1.98694011 -0.08483008]
 [-0.04755197  1.65394458  1.50096783]
 [-0.44728167 -0.58154161 -0.35285909]]
First set of A:
 [[0.64699755 0.56181861 0.85433287]
 [0.55135274 0.12058096 0.47880519]
 [0.48811425 0.83942346 0.81771878]
 [0.39000727 0.35857795 0.41268927]]
Second set of Z:
 [[2.66015237]
 [1.68341925]
 [2.5325112 ]
 [1.48438339]]
Second set of A:
 [[0.93463398]
 [0.84335677]
 [0.92638978]
 [0.81523375]]


In [19]:
## d. Loss Function
## Four seperate loss functions:
## Mean Squared Error, Mean Absolute Error, Huber Loss, Binary Cross Entropy
## We will use Mean Squared Error for our simple neural network

# Mean Squared Error
mse_loss = np.mean(np.square(A2 - y))

print(f"Mean Squared Error: {mse_loss}")

# Mean Absolute Error
mae_loss = np.mean(np.abs(A2 - y))

print(f"Mean Absolute Error: {mae_loss}")

# Huber Loss
huber_loss = np.where(np.abs(A2 - y) <= 1, 0.5 * np.square(A2 - y), np.abs(A2 - y) - 0.5)

print(f"Huber Loss: {huber_loss}")

# Binary Entropy Loss
bce_loss = -np.mean(y * np.log(A2) + (1 - y) * np.log(1 - A2))

print(f"Binary Cross Entropy Loss: {bce_loss}")


Mean Squared Error: 0.3920255772492692
Mean Absolute Error: 0.495030295820999
Huber Loss: [[0.43677033]
 [0.01226855]
 [0.00270923]
 [0.33230304]]
Binary Cross Entropy Loss: 1.1658104637259223


In [20]:
## e. Backpropagation

# Calculate the error for the output layer
d_A2 = (A2 - y)

# Calculate the derivative of the sigmoid for the output layer
d_Z2 = d_A2 * sigmoid_derivative(A2)

# Calculate gradients for weights2 and bias2
d_weights2 = np.dot(A1.T, d_Z2)
d_bias2 = np.sum(d_Z2, axis=0, keepdims=True)

# Calculate the error for the hidden layer
d_A1 = np.dot(d_Z2, weights2.T)

# Calculate the derivative of the sigmoid for the hidden layer
d_Z1 = d_A1 * sigmoid_derivative(A1)

# Calculate gradients for weights1 and bias1
d_weights1 = np.dot(X.T, d_Z1)
d_bias1 = np.sum(d_Z1, axis=0, keepdims=True)

print(f"Gradient for Weights1:\n {d_weights1}")
print(f"Gradient for Bias1:\n {d_bias1}")
print(f"Gradient for Weights2:\n {d_weights2}")
print(f"Gradient for Bias2:\n {d_bias2}")

Gradient for Weights1:
 [[0.04927192 0.0198739  0.03786533]
 [0.04246142 0.01877968 0.03210246]
 [0.06323319 0.02842598 0.04039956]]
Gradient for Bias1:
 [[0.06323319 0.02842598 0.04039956]]
Gradient for Weights2:
 [[0.07097554]
 [0.06940316]
 [0.08544641]]
Gradient for Bias2:
 [[0.15418351]]


In [22]:
## f. Weight Update

# Define a learning rate
learning_rate = 0.5

# Update weights and biases using gradient descent
weights1 -= learning_rate * d_weights1
bias1 -= learning_rate * d_bias1
weights2 -= learning_rate * d_weights2
bias2 -= learning_rate * d_bias2

print(f"Updated First set of Weights:\n {weights1}")
print(f"Updated First set of Bias:\n {bias1}")
print(f"Updated Second set of Weights:\n {weights2}")
print(f"Updated Second set of Bias:\n {bias2}")

Updated First set of Weights:
 [[-0.67805543  1.39546155 -0.28696168]
 [-0.4209604  -2.24487603 -1.86987814]
 [ 0.5742509   0.2343331   1.74879706]]
Updated First set of Bias:
 [[-0.0316166  -0.01421299 -0.02019978]]
Updated Second set of Weights:
 [[1.72678174]
 [0.6862388 ]
 [1.26230746]]
Updated Second set of Bias:
 [[-0.07709175]]


In [23]:
## g. Iterative Process of Foward and Back Propagation

epochs = 10000 # Number of training iterations
learning_rate = 0.1 # Re-defining learning rate, adjust as needed

# Re-initialize weights and biases for a fresh training run
weights1 = np.random.randn(3,3)
bias1 = np.zeros((1,3))
weights2 = np.random.randn(3,1)
bias2 = np.zeros((1,1))

print("Starting training...")
for epoch in range(epochs):
    # Forward Propagation
    Z1 = X @ weights1 + bias1
    A1 = sigmoid(Z1)
    Z2 = A1 @ weights2 + bias2
    A2 = sigmoid(Z2)

    # Loss Calculation (Mean Squared Error)
    mse_loss = np.mean(np.square(A2 - y))

    # Backpropagation
    d_A2 = (A2 - y)
    d_Z2 = d_A2 * sigmoid_derivative(A2)

    d_weights2 = np.dot(A1.T, d_Z2)
    d_bias2 = np.sum(d_Z2, axis=0, keepdims=True)

    d_A1 = np.dot(d_Z2, weights2.T)
    d_Z1 = d_A1 * sigmoid_derivative(A1)

    d_weights1 = np.dot(X.T, d_Z1)
    d_bias1 = np.sum(d_Z1, axis=0, keepdims=True)

    # Weight Update
    weights1 -= learning_rate * d_weights1
    bias1 -= learning_rate * d_bias1
    weights2 -= learning_rate * d_weights2
    bias2 -= learning_rate * d_bias2

    # Print loss every 1000 epochs
    if epoch % 1000 == 0:
        print(f"Epoch {epoch}, MSE Loss: {mse_loss:.4f}")

print("\nTraining complete!")
print(f"Final Predicted Output (A2):\n {A2}")
print(f"Final Mean Squared Error: {mse_loss:.4f}")

Starting training...
Epoch 0, MSE Loss: 0.2909
Epoch 1000, MSE Loss: 0.2080
Epoch 2000, MSE Loss: 0.0853
Epoch 3000, MSE Loss: 0.0185
Epoch 4000, MSE Loss: 0.0084
Epoch 5000, MSE Loss: 0.0052
Epoch 6000, MSE Loss: 0.0038
Epoch 7000, MSE Loss: 0.0029
Epoch 8000, MSE Loss: 0.0024
Epoch 9000, MSE Loss: 0.0020

Training complete!
Final Predicted Output (A2):
 [[0.02498583]
 [0.95409565]
 [0.96225884]
 [0.05157231]]
Final Mean Squared Error: 0.0017
